### PR TITLE
https://github.com/ComplianceAsCode/content/releases/tag/v0.1.70

### PR DESCRIPTION
**Pull request by jseiser**

### CODE REVIEW

**Comment by jseiser** [comment]
@dmc5179 

Another release was created upstream for RHEL 7 and 8.

Thanks.

**Comment by jseiser** [comment]
@dmc5179 

https://github.com/ComplianceAsCode/content/releases/tag/v0.1.67

**Comment by jseiser** [comment]
@redhatrises 
@RedHatDan 
@dmc5179 

Any chance we can get that latest Compliance as code release?

**Comment by jseiser** [comment]
@RedHatDan 
@redhatrises 
@dmc5179 

They have released 0.1.68 last month.

**Comment by jseiser** [comment]
@RedHatDan 
@redhatrises 
@dmc5179 

https://github.com/ComplianceAsCode/content/releases/tag/v0.1.70

**Comment by dmc5179** [comment]
Latest version, 0.1.71 has been pushed.

**Pull request closed without merging**
