### PR TITLE
ComplianceAsCode v0.1.61

### PR DESCRIPTION
**Pull request by jseiser**
Ignore this pull request..

I just had no other way of submitting an issue.

There has been a new release of the Compliance as Code project, but I do not see it reflected here, or the RHEL 8 repo.

https://github.com/ComplianceAsCode/content/releases/tag/v0.1.61

Is this project still maintained?

Thank you

### CODE REVIEW

**Comment by jseiser** [comment]
@dmc5179 
@RedHatDan 
@redhatrises 

Any chance to get the latest changes pulled in here?

**Comment by dmc5179** [comment]
@jseiser Started the build now. Should be able to push the updates today.

**Comment by jseiser** [comment]
@dmc5179 

Any chance this will just flow to Ansible Galaxy so the stig 7/8 releases there are available?

Also, is there a better way for me to notify new releases instead creating a fake pull req. and pinging you all?

Thanks so much for this BTW.

**Comment by jseiser** [comment]
@dmc5179 

Sorry to be a PITA, but the STIG8 repo still is missing the release, and the ansible galaxy version is also not updated.

Is there a better way to communicate these things?

Thanks.

**Comment by dmc5179** [comment]
@jseiser no worries. the compliance as code stuff changed quite a bit between 1.60 and 1.61 and the util that converts the playbooks to roles is not handling it well. I'll take a look

**Comment by jseiser** [comment]
@dmc5179 

Any update on this, or anything we can do to assist?


https://galaxy.ansible.com/redhatofficial/rhel8_stig is still on the old version.

**Comment by jseiser** [comment]
@dmc5179 
@RedHatDan 
@redhatrises 

Any update on this, or anything we can do to assist?  RHEL 8 STIG is not updated yet.

We rely heavily on these 2 ansible roles.

**Comment by dmc5179** [comment]
@jseiser Not sure why the util is having issues with this one role but I commented out the check that is having an issue and the role is updated now. Galaxy should update automatically but I'll check in a bit to make sure.

**Comment by jseiser** [comment]
@dmc5179 

Thanks for all your work.  Since we are heavily invested in this role, is there any way we can either assist, or atleast notify of new releases without having to create fake pull requests?

Thanks,

**Comment by jseiser** [comment]
@dmc5179 
@RedHatDan 
@redhatrises 

https://github.com/ComplianceAsCode/content/releases/tag/v0.1.62

There has been another new release

**Comment by dmc5179** [comment]
Yep, I just pushed the updates.

**Pull request closed without merging**
